# Generated by Django 4.2.7 on 2025-10-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('qualifier', 'Qualifier'), ('salesrep', 'SalesRep'), ('admin', 'Admin'), ('canvasser', 'Canvasser')], default='agent', help_text='User role for access control', max_length=20),
        ),
    ]
