# Generated by Django 4.2.7 on 2025-11-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('qualifier', 'Qualifier'), ('salesrep', 'SalesRep'), ('admin', 'Admin'), ('canvasser', 'Canvasser'), ('staff4dshire', 'Staff4dshire')], default='agent', help_text='User role for access control', max_length=20),
        ),
    ]
