services:
  - type: web
    name: margav-crm-backend
    env: python
    plan: starter
    buildCommand: |
      pip install -r backend/requirements.txt
      cd backend
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: cd backend && gunicorn crm_backend.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: margav-crm-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: margav-crm-backend.onrender.com,localhost,127.0.0.1
      - key: CORS_ALLOWED_ORIGINS
        value: https://margav-crm-frontend.onrender.com,http://localhost:3000,http://127.0.0.1:3000
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://margav-crm-backend.onrender.com/api/auth/google/callback
      - key: GOOGLE_SHEETS_SPREADSHEET_ID
        sync: false
      - key: GOOGLE_SHEETS_WORKSHEET_NAME
        value: Leads
      - key: GOOGLE_CALENDAR_EMAIL
        sync: false
      - key: DIALER_API_KEY
        sync: false

  - type: web
    name: margav-crm-frontend
    env: static
    plan: starter
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://margav-crm-backend.onrender.com

databases:
  - name: margav-crm-db
    plan: starter
