# Generated by Django 4.2.7 on 2025-10-02 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="disposition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_interested", "Not Interested"),
                    ("tenant", "Tenant"),
                    ("wrong_number", "Wrong Number"),
                    ("no_answer", "No Answer"),
                    ("callback_requested", "Callback Requested"),
                    ("do_not_call", "Do Not Call"),
                    ("other", "Other"),
                ],
                help_text="Disposition for non-interested leads",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="field_sales_rep",
            field=models.ForeignKey(
                blank=True,
                help_text="Field sales rep assigned to the appointment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="google_calendar_event_id",
            field=models.CharField(
                blank=True,
                help_text="Google Calendar event ID for synchronization",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="sale_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sale amount if sale is made",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("cold_call", "Cold Call"),
                    ("interested", "Interested"),
                    ("not_interested", "Not Interested"),
                    ("tenant", "Tenant"),
                    ("other_disposition", "Other Disposition"),
                    ("sent_to_kelly", "Sent to Kelly"),
                    ("qualified", "Qualified"),
                    ("appointment_set", "Appointment Set"),
                    ("appointment_completed", "Appointment Completed"),
                    ("sale_made", "Sale Made"),
                    ("sale_lost", "Sale Lost"),
                ],
                default="cold_call",
                help_text="Current status of the lead",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Dialer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the dialer is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Admin who created/activated the dialer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialer_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
