# Generated by Django 4.2.7 on 2025-10-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_lead_disposition_lead_field_sales_rep_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.UniqueConstraint(
                fields=("phone",), name="unique_phone_per_lead"
            ),
        ),
    ]
