# Generated by Django 4.2.7 on 2025-10-03 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leads", "0004_add_qualifier_status_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(help_text="Notification message")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("status_update", "Status Update"),
                            ("appointment_set", "Appointment Set"),
                            ("qualification_result", "Qualification Result"),
                        ],
                        default="status_update",
                        help_text="Type of notification",
                        max_length=30,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the agent has read this notification",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="Agent who receives this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        help_text="Lead this notification is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="leads.lead",
                    ),
                ),
                (
                    "qualifier",
                    models.ForeignKey(
                        help_text="Qualifier who sent this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
