# Generated by Django 4.2.7 on 2025-10-06 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leads", "0006_add_dialer_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DialerUserLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dialer_user_id",
                    models.CharField(
                        help_text="Stable unique identifier from dialer (e.g., user ID or login)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "dialer_username",
                    models.CharField(
                        blank=True,
                        help_text="Optional human-readable username from dialer for reference",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "crm_user",
                    models.OneToOneField(
                        help_text="Mapped CRM user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dialer_link",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dialer User Link",
                "verbose_name_plural": "Dialer User Links",
                "ordering": ["dialer_user_id"],
            },
        ),
    ]
