# Generated by Django 4.2.7 on 2025-10-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0007_dialeruserlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="day_night_rate",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No"), ("unsure", "Unsure")],
                help_text="Whether the lead has a day/night rate",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="energy_bill_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Specific energy bill amount if known",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="has_ev_charger",
            field=models.BooleanField(
                blank=True, help_text="Whether the lead has an EV charger", null=True
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="has_previous_quotes",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the lead has had previous quotes",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="previous_quotes_details",
            field=models.TextField(
                blank=True, help_text="Details about previous quotes if any", null=True
            ),
        ),
    ]
