# Generated by Django 4.2.7 on 2025-10-08 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leads", "0008_lead_day_night_rate_lead_energy_bill_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Callback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(help_text="When the callback is scheduled"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_answer", "No Answer"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        help_text="Current status of the callback",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the callback"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="Agent responsible for the callback",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="callbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        help_text="Lead associated with this callback",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="callbacks",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_time"],
                "unique_together": {("lead", "scheduled_time")},
            },
        ),
    ]
