# Generated by Django 4.2.7 on 2025-10-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_callback_deleted_by_alter_lead_deleted_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Callback',
        ),
    ]
