# Generated by Django 4.2.7 on 2025-10-13 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0012_remove_callback_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='Whether this object has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When this object was soft deleted', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for deletion', null=True)),
                ('scheduled_time', models.DateTimeField(help_text='When the callback should be made')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_answer', 'No Answer'), ('sent_to_qualifier', 'Sent to Qualifier')], default='scheduled', help_text='Current status of the callback', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the callback', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the callback was completed', null=True)),
                ('created_by', models.ForeignKey(help_text='Agent who created the callback', on_delete=django.db.models.deletion.CASCADE, related_name='created_callbacks', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(help_text='Lead requesting the callback', on_delete=django.db.models.deletion.CASCADE, related_name='callbacks', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Callback',
                'verbose_name_plural': 'Callbacks',
                'ordering': ['scheduled_time'],
            },
        ),
    ]
