# Generated by Django 4.2.7 on 2025-10-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_callback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('cold_call', 'Cold Call'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('tenant', 'Tenant'), ('other_disposition', 'Other Disposition'), ('sent_to_kelly', 'Sent to Kelly'), ('qualified', 'Qualified'), ('appointment_set', 'Appointment Set'), ('appointment_completed', 'Appointment Completed'), ('sale_made', 'Sale Made'), ('sale_lost', 'Sale Lost'), ('no_contact', 'No Contact'), ('blow_out', 'Blow Out'), ('callback', 'Call Back'), ('pass_back_to_agent', 'Pass Back to Agent'), ('pass_back', 'Pass Back'), ('desk_top_survey', 'Desk Top Survey'), ('on_hold', 'On Hold'), ('sold', 'Sold')], default='cold_call', help_text='Current status of the lead', max_length=30),
        ),
    ]
