# Generated by Django 4.2.7 on 2025-10-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_update_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_number',
            field=models.CharField(blank=True, help_text='Custom lead number (e.g., ME001, ME002)', max_length=20, null=True, unique=True),
        ),
    ]
