# Generated by Django 4.2.7 on 2025-10-22 08:56

from django.db import migrations, models


def set_default_postal_code(apps, schema_editor):
    """
    Set default postal code for existing leads that have null postal_code.
    """
    Lead = apps.get_model('leads', 'Lead')
    # Update all leads with null postal_code to have a default value
    Lead.objects.filter(postal_code__isnull=True).update(postal_code='Unknown')


def reverse_set_default_postal_code(apps, schema_editor):
    """
    Reverse migration - set postal_code back to null for leads with 'Unknown'.
    """
    Lead = apps.get_model('leads', 'Lead')
    Lead.objects.filter(postal_code='Unknown').update(postal_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_add_qualifier_callback_status'),
    ]

    operations = [
        # First, set default values for existing null postal_code fields
        migrations.RunPython(
            set_default_postal_code,
            reverse_set_default_postal_code,
        ),
        # Then, make the field non-nullable
        migrations.AlterField(
            model_name='lead',
            name='postal_code',
            field=models.CharField(max_length=20, help_text='Postal code of the lead'),
        ),
    ]
