# Generated by Django 4.2.7 on 2025-10-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_fieldsubmission_lead_field_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldsubmission',
            name='photos',
            field=models.JSONField(default=dict, help_text='Base64 encoded photos (dict with keys: roof, frontRear, energyBill)'),
        ),
    ]
