# Generated by Django 4.2.7 on 2025-10-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_alter_fieldsubmission_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldsubmission',
            name='city',
        ),
        migrations.RemoveField(
            model_name='fieldsubmission',
            name='heating_type',
        ),
        migrations.RemoveField(
            model_name='fieldsubmission',
            name='hot_water_type',
        ),
        migrations.RemoveField(
            model_name='fieldsubmission',
            name='insulation_type',
        ),
        migrations.RemoveField(
            model_name='fieldsubmission',
            name='monthly_bill',
        ),
        migrations.RemoveField(
            model_name='fieldsubmission',
            name='occupancy',
        ),
        migrations.RemoveField(
            model_name='fieldsubmission',
            name='property_age',
        ),
        migrations.RemoveField(
            model_name='fieldsubmission',
            name='windows_type',
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='assessment_date',
            field=models.CharField(blank=True, default='', help_text='Date of assessment', max_length=50),
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='assessment_time',
            field=models.CharField(blank=True, default='', help_text='Time of assessment', max_length=50),
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='average_monthly_bill',
            field=models.CharField(blank=True, help_text='Average monthly energy bill', max_length=50),
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='canvasser_name',
            field=models.CharField(blank=True, default='', help_text='Canvasser full name', max_length=255),
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='electric_heating_details',
            field=models.TextField(blank=True, help_text='Electric heating details'),
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='energy_type',
            field=models.CharField(blank=True, choices=[('gas', 'Gas Only'), ('electric', 'Electric Only'), ('dual', 'Dual (Gas & Electric)')], help_text='Type of energy (gas/electric/dual)', max_length=20),
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='has_received_other_quotes',
            field=models.CharField(blank=True, help_text='Has received other quotes? (yes/no)', max_length=10),
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='is_decision_maker',
            field=models.CharField(blank=True, help_text='Is decision maker? (yes/no)', max_length=10),
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='moving_in_5_years',
            field=models.CharField(blank=True, help_text='Moving in 5 years? (yes/no)', max_length=10),
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='number_of_bedrooms',
            field=models.CharField(blank=True, help_text='Number of bedrooms', max_length=10),
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='owns_property',
            field=models.CharField(blank=True, help_text='Does customer own property? (yes/no)', max_length=10),
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='preferred_contact_time',
            field=models.CharField(blank=True, help_text='Preferred contact time', max_length=50),
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='roof_material',
            field=models.CharField(blank=True, choices=[('tiled', 'Tiled'), ('slate', 'Slate'), ('metal', 'Metal'), ('felt', 'Felt'), ('other', 'Other')], help_text='Material of roof', max_length=20),
        ),
        migrations.AddField(
            model_name='fieldsubmission',
            name='uses_electric_heating',
            field=models.CharField(blank=True, help_text='Uses electric heating? (yes/no)', max_length=10),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='postal_code',
            field=models.CharField(help_text='Postal code', max_length=20),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='roof_type',
            field=models.CharField(blank=True, choices=[('pitched', 'Pitched'), ('flat', 'Flat'), ('mixed', 'Mixed')], help_text='Type of roof', max_length=20),
        ),
    ]
