# Generated by Django 4.2.7 on 2025-10-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_remove_fieldsubmission_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldsubmission',
            name='address',
            field=models.TextField(blank=True, help_text='Property address', null=True),
        ),
    ]
