# Generated by Django 4.2.7 on 2025-10-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_make_address_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldsubmission',
            name='signature',
        ),
    ]
