# Generated by Django 4.2.7 on 2025-11-12 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0023_remove_signature_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldsubmission',
            name='photos',
            field=models.JSONField(default=dict, help_text='Base64 encoded photos (dict with keys: frontRoof, rearRoof, sideRoof, energyBill, additional array)'),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='roof_material',
            field=models.CharField(blank=True, choices=[('tiled', 'Tiled'), ('slate', 'Slate'), ('metal', 'Metal'), ('rosemary', 'Rosemary'), ('other', 'Other')], help_text='Material of roof', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='Agent assigned to this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
