# Generated by Django 4.2.7 on 2025-11-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_add_lead_form_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='aged_18_70',
            field=models.BooleanField(blank=True, help_text='Is customer aged between 18 & 70?', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='available_3_working_days',
            field=models.BooleanField(blank=True, help_text='Is customer available for appointment within next 3 working days?', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='both_homeowners_present',
            field=models.BooleanField(blank=True, help_text='Will both homeowners be present on appointment day?', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='building_work_ongoing',
            field=models.BooleanField(blank=True, help_text='Any building work ongoing or planned in next 6 months?', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='conservation_area',
            field=models.BooleanField(blank=True, help_text='Is the property in a conservation area?', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='current_electric_bill_type',
            field=models.CharField(blank=True, choices=[('electric', 'Electric'), ('gas', 'Gas'), ('dual', 'Dual')], help_text='Current electric bill type', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='currently_employed',
            field=models.BooleanField(blank=True, help_text='Is the customer currently employed?', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer_age',
            field=models.IntegerField(blank=True, help_text='Customer age (must be between 18-70)', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='customer_aware_no_grants',
            field=models.BooleanField(blank=True, help_text='Customer aware there are NO grants for solar?', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='desktop_roof_check_completed',
            field=models.BooleanField(blank=True, help_text='Desktop roof check completed - minimum 8 panels suitable', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='earns_over_12k',
            field=models.BooleanField(blank=True, help_text='Do they earn over £12K per year?', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='has_good_credit',
            field=models.BooleanField(blank=True, help_text='Do they have good credit?', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='planning_to_move_5_years',
            field=models.BooleanField(blank=True, help_text='Are they planning to move within 5 years?', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_listed',
            field=models.BooleanField(blank=True, help_text='Is the property listed?', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_type_qualifier',
            field=models.CharField(blank=True, choices=[('detached', 'Detached'), ('semi-detached', 'Semi-Detached'), ('terraced', 'Terrace'), ('bungalow', 'Bungalow'), ('caravan', 'Caravan'), ('commercial', 'Commercial'), ('other', 'Other')], help_text='Property type for qualifier', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='roof_shaded_obstructed',
            field=models.BooleanField(blank=True, help_text='Is the roof shaded or obstructed?', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='roof_type_qualifier',
            field=models.CharField(blank=True, choices=[('hip', 'Hip'), ('gable', 'Gable'), ('flat', 'Flat')], help_text='Roof type for qualifier', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='speaking_to_homeowner',
            field=models.BooleanField(blank=True, help_text='Are you speaking to the homeowner?', null=True),
        ),
    ]
