# Generated by Django 4.2.7 on 2025-11-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_add_qualifier_lead_sheet_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='qualifier_callback_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled qualifier callback date and time', null=True),
        ),
    ]
