# Generated by Django 4.2.7 on 2025-11-21 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0027_add_qualifier_lead_sheet_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_call_sid', models.CharField(blank=True, help_text='Twilio Call SID', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('ringing', 'Ringing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('cancelled', 'Cancelled')], default='initiated', help_text='Current call status', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the call was initiated')),
                ('answered_at', models.DateTimeField(blank=True, help_text='When the call was answered', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the call ended', null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Call duration in seconds')),
                ('transcript', models.TextField(blank=True, help_text='Full call transcript', null=True)),
                ('qualification_summary', models.TextField(blank=True, help_text='AI-generated qualification summary', null=True)),
                ('qualification_data', models.JSONField(blank=True, default=dict, help_text='Structured qualification data from AI')),
                ('recording_url', models.URLField(blank=True, help_text='URL to call recording if available', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if call failed', null=True)),
                ('gateway_url', models.URLField(blank=True, help_text='WebSocket URL for the AI voice gateway', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who initiated the call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_calls', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(help_text='Lead this call is for', on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Call Log',
                'verbose_name_plural': 'Call Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField(help_text='Scheduled appointment date and time')),
                ('notes', models.TextField(blank=True, help_text='Appointment notes', null=True)),
                ('confirmed', models.BooleanField(default=False, help_text='Whether the appointment has been confirmed')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the appointment was confirmed', null=True)),
                ('cancelled', models.BooleanField(default=False, help_text='Whether the appointment was cancelled')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the appointment was cancelled', null=True)),
                ('completed', models.BooleanField(default=False, help_text='Whether the appointment was completed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the appointment was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_log', models.ForeignKey(blank=True, help_text='Call log that led to this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='leads.calllog')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(help_text='Lead this appointment is for', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['scheduled_datetime'],
            },
        ),
    ]
