# Generated by Django 4.2.7 on 2025-11-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_add_qualifier_callback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='qualifier_notes',
            field=models.TextField(blank=True, help_text='Qualifier-specific notes about the lead qualification', null=True),
        ),
    ]
