# Generated by Django 4.2.7 on 2025-11-21 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_calllog_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICallQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0, help_text='Priority level (higher = more priority)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_queue', 'In Queue'), ('calling', 'Calling'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', help_text='Current status in queue', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='When to call this lead (optional)', null=True)),
                ('attempts', models.IntegerField(default=0, help_text='Number of call attempts')),
                ('max_attempts', models.IntegerField(default=3, help_text='Maximum number of attempts')),
                ('notes', models.TextField(blank=True, help_text='Notes about this queue entry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_log', models.ForeignKey(blank=True, help_text='Call log if call was initiated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entry', to='leads.calllog')),
                ('lead', models.ForeignKey(help_text='Lead in the queue', on_delete=django.db.models.deletion.CASCADE, related_name='ai_call_queue_entries', to='leads.lead')),
            ],
            options={
                'verbose_name': 'AI Call Queue Entry',
                'verbose_name_plural': 'AI Call Queue Entries',
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
