# Generated by Django 4.2.7 on 2025-11-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_add_simplified_form_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldsubmission',
            name='age_range',
            field=models.CharField(blank=True, help_text='Age range (18-74/outside_range)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='electric_bill',
            field=models.CharField(blank=True, help_text='Electric bill amount', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='is_decision_maker',
            field=models.CharField(blank=True, help_text='Is customer the decision maker? (yes/no/partner)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='owns_property',
            field=models.CharField(blank=True, help_text='Does customer own the property? (yes/no)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='has_received_other_quotes',
            field=models.CharField(blank=True, help_text='Has received other quotes? (yes/no)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='preferred_contact_time',
            field=models.CharField(blank=True, help_text='Preferred contact time', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='assessment_date',
            field=models.CharField(blank=True, help_text='Assessment date', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='assessment_time',
            field=models.CharField(blank=True, help_text='Assessment time', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='canvasser_name',
            field=models.CharField(blank=True, help_text='Canvasser name', max_length=255, null=True),
        ),
    ]
