# Generated by Django 4.2.7 on 2025-11-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_allow_null_simplified_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldsubmission',
            name='assessment_date',
            field=models.CharField(blank=True, help_text='Date of assessment', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='assessment_time',
            field=models.CharField(blank=True, help_text='Time of assessment', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='canvasser_name',
            field=models.CharField(blank=True, help_text='Canvasser full name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='owns_property',
            field=models.CharField(blank=True, help_text='Does customer own property? (yes/no)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='is_decision_maker',
            field=models.CharField(blank=True, help_text='Is customer the decision maker? (yes/no/partner)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fieldsubmission',
            name='preferred_contact_time',
            field=models.CharField(blank=True, help_text='Preferred contact time', max_length=20, null=True),
        ),
        # Note: age_range and electric_bill already exist from migration 0030
        # We're just ensuring the model in models.py has them defined
    ]
